[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cheby_bench_gen.workspace = true
cheby_test_support.workspace = true
clap.workspace = true
serde_json.workspace = true

[lints]
workspace = true
