[package]
name = "cheby_driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cheby_diag.workspace = true
cheby_syntax.workspace = true
cheby_package.workspace = true
cheby_resolve.workspace = true
cheby_iface.workspace = true
cheby_types.workspace = true
cheby_mir.workspace = true
cheby_codegen_clif.workspace = true
cheby_jit.workspace = true
cheby_link.workspace = true
cheby_js.workspace = true
cheby_consteval.workspace = true

[lints]
workspace = true
