[package]
name = "cheby_lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cheby_driver.workspace = true
cheby_syntax.workspace = true
cheby_fmt.workspace = true

[lints]
workspace = true
